default_language_version:
  python: python3
repos:
  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        additional_dependencies: [flake8-print]
        args:
          [
            "--enable=T",
            "--max-line-length=120",
            "--select=E,W,F",
            "--ignore=W503",
          ]
        exclude: __init__.py
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: debug-statements
